name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  test:
    name: Test on Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#ci-cd'
          config: .github/config/slack.yml
        if: always()
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#ci-cd'
          config: .github/config/slack.yml
        if: always()
